// Stub for Playwright test environment — satisfies _v41_loadStatusScript first-fallback path
// so 404 cascade doesn't fail the no-console-errors diagnostic.
// In production this file lives next to the bible in ~/Downloads/ and is regenerated by the routine baker.
window.ROUTINE_STATUS = {};
