import { test, expect } from '@playwright/test';
import * as path from 'path';

const URL = 'file://' + path.resolve(__dirname, '..', 'bible.html');

// v125 — the Colossal Ancient Statue tracker gadget gains routable cells WITHOUT
// losing its collect glow/tally. Each of the 5 tiles now has 3 distinct click zones:
//   • the ✓ badge (.statue-check) + tile background → toggleStatue (glow/tally)
//   • the statue name → openDrop(statue) → its statue ID card
//   • the boss "from" row → openBossDetail(bossId) → that boss's ID card (NEW, art0r'd)
// All 5 tiles (incl. Madawc's Ire → Mephisto) are generated by one identical loop and
// must behave identically — this guards against the reported "Madawc's tile" confusion.
test.describe('v125 statue tracker — routable cells + collect toggle', () => {
  const TILES = [
    { n: "Talic's Anguish", bossId: 'andariel' },
    { n: "Korlic's Pain", bossId: 'duriel' },
    { n: "Madawc's Ire", bossId: 'mephisto' },
    { n: "Bul-Kathos' Nightmare", bossId: 'diablo' },
    { n: "Worusk's End", bossId: 'baal' },
  ];

  test.beforeEach(async ({ page }) => {
    await page.goto(URL);
    await page.waitForTimeout(1000);
    await page.evaluate(() => (window as any).renderStatueTracker());
    await page.waitForTimeout(100);
  });

  test('every tile carries the 3 click zones with art0r on both names', async ({ page }) => {
    const cards = await page.evaluate(() => {
      const root = document.getElementById('statue-tracker')!;
      return Array.from(root.querySelectorAll('.statue-card')).map((c) => ({
        check: !!c.querySelector('.statue-check'),
        nameOnclick: c.querySelector('.statue-card-name')?.getAttribute('onclick') || '',
        nameImg: !!c.querySelector('.statue-card-name .d2art-img'),
        fromOnclick: c.querySelector('.statue-card-from')?.getAttribute('onclick') || '',
        fromImg: !!c.querySelector('.statue-card-from .d2art-img'),
      }));
    });
    expect(cards.length).toBe(5);
    cards.forEach((c, i) => {
      expect(c.check, `${TILES[i].n} has collect badge`).toBe(true);
      expect(c.nameOnclick, `${TILES[i].n} name routes via openDrop`).toContain('openDrop(');
      expect(c.nameOnclick, `${TILES[i].n} name stops propagation`).toContain('stopPropagation');
      expect(c.nameImg, `${TILES[i].n} name art0r portrait`).toBe(true);
      expect(c.fromOnclick, `${TILES[i].n} boss routes via openBossDetail`).toContain('openBossDetail(');
      expect(c.fromOnclick, `${TILES[i].n} boss stops propagation`).toContain('stopPropagation');
      expect(c.fromImg, `${TILES[i].n} boss art0r portrait`).toBe(true);
    });
  });

  test('each tile routes to the CORRECT boss ID card (incl. Madawc → Mephisto)', async ({ page }) => {
    const r = await page.evaluate(() => {
      const root = document.getElementById('statue-tracker')!;
      return Array.from(root.querySelectorAll('.statue-card .statue-card-from')).map(
        (f) => f.getAttribute('onclick') || ''
      );
    });
    TILES.forEach((t, i) => {
      expect(r[i], `${t.n} → openBossDetail('${t.bossId}')`).toContain(`openBossDetail&&window.openBossDetail('${t.bossId}')`);
    });
  });

  test('the collect toggle (glow/tally) works for all 5 tiles incl. Madawc', async ({ page }) => {
    for (const t of TILES) {
      const r = await page.evaluate((name) => {
        const root = document.getElementById('statue-tracker')!;
        const before = root.querySelectorAll('.statue-card.collected').length;
        (window as any).toggleStatue(name);
        const mid = root.querySelectorAll('.statue-card.collected').length;
        (window as any).toggleStatue(name); // toggle back off
        const after = root.querySelectorAll('.statue-card.collected').length;
        return { before, mid, after };
      }, t.n);
      expect(r.mid, `${t.n} tallies on`).toBe(r.before + 1);
      expect(r.after, `${t.n} tallies off`).toBe(r.before);
    }
  });

  test('opening a statue + a boss card from the tracker throws no console errors', async ({ page }) => {
    const errs: string[] = [];
    page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
    await page.evaluate(() => (window as any).openDrop("Madawc's Ire"));
    await page.waitForTimeout(60);
    await page.evaluate(() => (window as any).openBossDetail('mephisto'));
    await page.waitForTimeout(60);
    expect(errs).toEqual([]);
  });
});
