# -*- coding: utf-8 -*-
"""#174 v-B2 — THE CHARACTER BUILDER'S ITEM DATABASE, TAKEN FROM HIS OWN INSTALL, WRITTEN INTO THE BOARD.

His words: "if i click on helmet lets say.. it shold give me the options from the entire database to put as a
helmet or runeword and based on the base item.. exactly like the d2r one to one". The board had no such database:
ITEM_CODEX holds 320 names and ITEM_TIP 301, while the game he plays (Reign of the Warlock) has ~440 uniques, 140
set items, 181 runewords, every crafted recipe and every base. A picker that offered only what the board happened
to have typed would be a picker that lies by omission.

So this file pulls the game's own excel tables and display strings from the CASC of the install on this machine
(the same `_pull` tv/item_tables.py and tv/mule_slot_map.py use), and writes ONE generated JSON block into
bible.html between two markers:

    python3 tv/char_builder_db.py            # --check: is the block in bible.html what the install says?
    python3 tv/char_builder_db.py --write    # regenerate it (atomic, honours bible.html.EDIT_LOCK)

WHAT IS IN IT, AND WHERE EACH FACT COMES FROM
  · cls   the classes, in charstats.txt order (the game's class index), with the strings the game prints for
          "+N to <Class> Skill Levels", the three skill tabs and "(<Class> Only)"
  · ty    every item type the doll or the inventory can hold: its UI category (itemtypes.txt `UICategory`, the
          game's own grouping — pelts are `druid`, primal helms `barbh`), the class that alone may use it
          (`Class` through the `Equiv` chain) and its socket ceiling by item level (`MaxSockets1..3` with
          their level thresholds)
  · rail  per doll slot, which UI categories it takes — the slot's "base categories" the picker's left rail lists
  · b     every base: display name (item-names.json), type, tier and its normal/exceptional/elite family
          (`normcode`/`ubercode`/`ultracode`), sockets (`gemsockets`), requirements, defense or damage, which
          hands it needs (weapons.txt `2handed`/`1or2handed`), its inventory size, whether it can be ethereal
          (it has durability — an item with none cannot be)
  · it    every unique (uniqueitems.txt, the disabled ones left out), set item (setitems.txt), runeword
          (runes.txt `complete` = 1, with the item types it may be made in and the ones excluded) and crafted
          recipe (cubemain.txt rows that output a crafted item), each with its PROPERTY LINES rendered from the
          game's own words: properties.txt maps a property to its stats, itemstatcost.txt says how each stat is
          described (`descfunc` / `descstrpos` / `descpriority`), and item-modifiers.json holds the text — "All
          Resistances %+d", "%d%% Chance to cast level %d %s on striking". A rolled value is a RANGE the page
          draws as a box; a fixed one is a number.
  · sk    what fits a socket: every rune and gem (gems.txt: its weapon / helm-and-armor / shield modifiers)
  · T     the line templates, stored once and referenced by index (the block is ~40% smaller for it)

A ROLL'S KEY IS THE GAME'S. Each rolled value carries the column it comes from — `p3` is uniqueitems.txt
prop3 / setitems.txt prop3 / runes.txt T1Code3 / cubemain.txt `mod 3`, `a2b` a set item's aprop2b. The builder
stores a typed roll under that key (d2r_charBuilds ...slots[slot].rolls = {p3: 25}), so the stats engine, which
reads the same tables, can join a typed roll to the property it belongs to without parsing any text.

⚠ WHAT IS NOT HERE, SAID RATHER THAN FILLED: a property the tables name but do not describe (RotW's sunder-charm
affix groups, a few commented-out rows) becomes an UNKNOWN line naming its code — never dropped, never guessed.
A monster a reanimate property names is its id, not its name (monstats is not read). A magic jewel's or a
crafted item's RANDOM affixes are not listed: only what the recipe guarantees.

⚠ NO INSTALL = UNKNOWN (exit 77), never "the block is fine". The block is still checked in CI without one:
test_the_character_builder_is_their_builder.py proves every base, unique, set item and runeword name in it is
the name the committed tv/item_tables.json carries for it. [[unknown-stays-unknown]] [[copy-drift]]
"""
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if HERE not in sys.path:
    sys.path.insert(0, HERE)
try:
    from console_safe import enable as _console_safe
    _console_safe()
except Exception:
    pass                      # console encoding only; a failure here changes no fact the block holds

SKIP = 77
BIBLE = os.path.join(ROOT, "bible.html")
LOCK = BIBLE + ".EDIT_LOCK"
MARK_OPEN = "<!-- ⟦CB_DB⟧ GENERATED by tv/char_builder_db.py --write"
MARK_CLOSE = "<!-- ⟦/CB_DB⟧ -->"
BLOCK_ID = "cb-db"

_X = "data:data\\global\\excel\\"
_S = "data:data\\local\\lng\\strings\\"
#: (label, CASC path). ORDER IS FIXED — sourceHash is computed over it.
SOURCES = [
    ("armor", _X + "armor.txt"), ("weapons", _X + "weapons.txt"), ("misc", _X + "misc.txt"),
    ("itemtypes", _X + "itemtypes.txt"), ("uniqueitems", _X + "uniqueitems.txt"),
    ("setitems", _X + "setitems.txt"), ("sets", _X + "sets.txt"), ("runes", _X + "runes.txt"),
    ("gems", _X + "gems.txt"), ("properties", _X + "properties.txt"), ("itemstatcost", _X + "itemstatcost.txt"),
    ("skills", _X + "skills.txt"), ("skilldesc", _X + "skilldesc.txt"), ("charstats", _X + "charstats.txt"),
    ("playerclass", _X + "playerclass.txt"), ("cubemain", _X + "cubemain.txt"),
    ("itemnames", _S + "item-names.json"), ("itemrunes", _S + "item-runes.json"),
    ("itemmods", _S + "item-modifiers.json"), ("skillnames", _S + "skills.json"),
]

#: the doll's slots (the game's BodyLoc codes, the same keys the mule window uses) and the inventory
SLOTS = ("head", "neck", "tors", "rarm", "larm", "rrin", "lrin", "belt", "feet", "glov")
#: UI category (itemtypes.txt `UICategory`) -> the words the rail prints. PRESENTATION ONLY: which categories a
#: slot takes, and which bases and items sit in each, is the data's; these are plural English labels.
UI_LABEL = {
    "helms": "Helmets", "circl": "Circlets", "druid": "Pelts", "barbh": "Primal Helms", "armor": "Body Armor",
    "shlds": "Shields", "palad": "Auric Shields", "necro": "Voodoo Heads", "warlo": "Grimoires",
    "glove": "Gloves", "boots": "Boots", "belts": "Belts", "amule": "Amulets", "rings": "Rings",
    "axes": "Axes", "sword": "Swords", "daggs": "Daggers", "maces": "Maces", "scept": "Scepters",
    "wands": "Wands", "stave": "Staves", "bows": "Bows", "xbows": "Crossbows", "spear": "Spears",
    "poles": "Polearms", "javel": "Javelins", "throw": "Throwing Weapons", "assas": "Claws", "sorce": "Orbs",
    "amazo": "Amazon Weapons", "ammo": "Quivers", "jewel": "Jewels",
}
#: which UI categories each doll slot takes, in the rail's order. The categories themselves come from the data
#: (a type whose UICategory is `druid` is a pelt because the game says so); this is only which slot shows which.
SLOT_UI = {
    "head": ["helms", "circl", "druid", "barbh"],
    "tors": ["armor"],
    "rarm": ["axes", "sword", "daggs", "maces", "scept", "wands", "stave", "spear", "poles", "javel", "throw",
             "bows", "xbows", "assas", "sorce", "amazo"],
    "larm": ["shlds", "palad", "necro", "warlo", "ammo", "assas", "@offhand"],
    "glov": ["glove"], "feet": ["boots"], "belt": ["belts"], "neck": ["amule"], "rrin": ["rings"],
    "lrin": ["rings"],
}
#: the inventory's rail: charms by their type, each labelled by the BASE the game names (cm2 "Large Charm" is the
#: type `mcha`, "Medium Charm" — naming the rail by the type would print the wrong word)
INV_TYPES = ("scha", "mcha", "lcha", "csch")
#: two display names, one item: which property tells the duplicates apart (Rainbow Facet x8)
DUP_WORD = {"extra-fire": "Fire", "extra-cold": "Cold", "extra-ltng": "Lightning", "extra-pois": "Poison",
            "death-skill": "on Death", "levelup-skill": "on Level-up"}
_PULLED = {}


def _pull_all():
    """{label: bytes or None}. CB_DB_FROM=<dir> reads <dir>/<label>.<txt|json> instead (a local copy of the same
    tables, for iteration); the sourceHash is over the bytes either way, so a copy that differs says so."""
    if _PULLED:
        return _PULLED
    src_dir = os.environ.get("CB_DB_FROM")
    if src_dir:
        for label, path in SOURCES:
            p = os.path.join(src_dir, label + (".json" if path.endswith(".json") else ".txt"))
            _PULLED[label] = open(p, "rb").read() if os.path.exists(p) else None
        return _PULLED
    import item_tables as IT
    for label, path in SOURCES:
        _PULLED[label] = IT._pull(path)
    return _PULLED


def _rows(blob):
    import item_tables as IT
    return IT._rows(blob) or []


def _strings(*blobs):
    import item_tables as IT
    out = {}
    for b in blobs:
        m = IT._strings(b) or {}
        for k, v in m.items():
            out.setdefault(k, v)
    return out


def _int(s, d=0):
    s = str(s if s is not None else "").strip()
    try:
        return int(s)
    except ValueError:
        try:
            return int(float(s))
        except ValueError:
            return d


def _pois(v, frames):
    """poison is stored per frame in 256ths; the tooltip prints the total, rounded as the game rounds it
    (Blacktongue: 192 x 150 frames -> 113, not 112)"""
    return (int(v) * int(frames) + 128) // 256


def source_hash(blobs):
    h = hashlib.sha256()
    for label, _ in SOURCES:
        b = blobs.get(label)
        h.update(label.encode())
        h.update(b"\0")
        h.update(hashlib.sha256(b or b"").digest())
    return h.hexdigest()


class _Tpl(object):
    """the template table: every distinct line text stored once"""

    def __init__(self):
        self.list, self.ix = [], {}

    def id(self, t):
        if t not in self.ix:
            self.ix[t] = len(self.list)
            self.list.append(t)
        return self.ix[t]


def _printf(fmt, vals):
    """C format -> the block's template. %+d -> {+N}, %d / %i -> {N}, %s -> the literal given, %% -> %.
    `vals` is a list: an int means a placeholder index; a str is substituted literally."""
    out, i, n = [], 0, 0
    while i < len(fmt):
        c = fmt[i]
        if c != "%":
            out.append(c)
            i += 1
            continue
        j = i + 1
        if j < len(fmt) and fmt[j] == "%":
            out.append("%")
            i = j + 1
            continue
        m = re.match(r"%(\+?)(\d*)([dis])", fmt[i:])
        if not m:
            # D2R's reanimate string uses %0 / %1 (positional); treat as a value / a literal
            m2 = re.match(r"%(\d)", fmt[i:])
            if m2:
                v = vals[int(m2.group(1))] if int(m2.group(1)) < len(vals) else ""
                out.append(("{%d}" % v) if isinstance(v, int) else str(v))
                i += 2
                continue
            out.append(c)
            i += 1
            continue
        v = vals[n] if n < len(vals) else ""
        n += 1
        if m.group(3) == "s" or not isinstance(v, int):
            out.append(str(v))
        else:
            out.append("{%s%d}" % ("+" if m.group(1) else "", v))
        i += len(m.group(0))
    return "".join(out)


class DB(object):
    def __init__(self, blobs):
        self.blobs = blobs
        self.S = _strings(blobs.get("itemnames"), blobs.get("itemrunes"), blobs.get("itemmods"),
                          blobs.get("skillnames"))
        self.T = _Tpl()
        self.P = dict((r["code"], r) for r in _rows(blobs["properties"]) if r.get("code"))
        self.I = dict((r["Stat"], r) for r in _rows(blobs["itemstatcost"]) if r.get("Stat"))
        self.types = dict((r["Code"], r) for r in _rows(blobs["itemtypes"]) if r.get("Code"))
        self.skills_by_id, self.skills_by_name = {}, {}
        sd = dict((r.get("skilldesc"), r) for r in _rows(blobs["skilldesc"]) if r.get("skilldesc"))
        for r in _rows(blobs["skills"]):
            if not r.get("skill"):
                continue
            d = sd.get(r.get("skilldesc") or "")
            nm = self.S.get((d or {}).get("str name") or "") or r["skill"]
            rec = (nm, r.get("charclass") or "")
            self.skills_by_id[_int(r.get("*Id"), -1)] = rec
            self.skills_by_name[r["skill"].lower()] = rec
        self.classes = []
        codes = [r.get("Code") for r in _rows(blobs["playerclass"])]
        for i, r in enumerate(_rows(blobs["charstats"])):
            if r.get("class") == "Expansion" or not r.get("StrAllSkills"):
                continue
            code = codes[i] if i < len(codes) else ""
            self.classes.append({
                "n": r["class"], "c": code, "all": self.S.get(r["StrAllSkills"], ""),
                "tabs": [self.S.get(r.get("StrSkillTab%d" % k) or "", "") for k in (1, 2, 3)],
                "only": self.S.get(r.get("StrClassOnly") or "", ""),
                "attr": [_int(r.get(a)) for a in ("str", "dex", "int", "vit")]})
        self.cls_by_code = dict((c["c"], i) for i, c in enumerate(self.classes))

    # ---- item types -------------------------------------------------------------------------------------------
    def walk(self, code, col, seen=()):
        r = self.types.get(code)
        if not r or code in seen:
            return ""
        if r.get(col):
            return r[col]
        for e in (r.get("Equiv1"), r.get("Equiv2")):
            if e:
                v = self.walk(e, col, seen + (code,))
                if v:
                    return v
        return ""

    def ancestors(self, code, seen=None):
        seen = set() if seen is None else seen
        if not code or code in seen:
            return seen
        seen.add(code)
        r = self.types.get(code) or {}
        for e in (r.get("Equiv1"), r.get("Equiv2")):
            if e:
                self.ancestors(e, seen)
        return seen

    # ---- property text ----------------------------------------------------------------------------------------
    def skill(self, par):
        if par is None or str(par).strip() == "":
            return None
        p = str(par).strip()
        if re.match(r"^-?\d+$", p):
            return self.skills_by_id.get(int(p))
        return self.skills_by_name.get(p.lower())

    def class_only(self, cc):
        i = self.cls_by_code.get(cc)
        return self.classes[i]["only"] if i is not None else ""

    def lines(self, props, set_bonus=False):
        """props = [(key, code, par, min, max)] -> [[tpl, ranges, prio, flag]]. flag 0 plain · 1 set bonus ·
        2 UNKNOWN (the tables do not describe it) · 3 a flag the item carries (ethereal)."""
        out = []
        have = {}
        for (key, code, par, lo, hi) in props:
            have.setdefault(code, (key, par, lo, hi))
        used = set()
        flag = 1 if set_bonus else 0

        def rng(a, b, key):
            a, b = _int(a), _int(b)
            if b < a:
                b = a
            return [a, b, key]

        cur = [""]                                        # the property code the next line belongs to

        def emit(fmt, vals, ranges, prio, f=None):
            out.append([self.T.id(_printf(fmt, vals)), ranges, prio, flag if f is None else f, cur[0]])

        def stat_prio(st):
            return _int((self.I.get(st) or {}).get("descpriority"), 0)

        # the game's own merges: a damage pair is one line; poison is per-frame over a length
        def pair(mn, mx, ln, word, rng_key, single_key, prio_stat):
            a, b = have.get(mn), have.get(mx)
            if not (a and b):
                return False
            used.update([mn, mx])
            cur[0] = mn
            ra, rb = rng(a[2], a[3], a[0]), rng(b[2], b[3], b[0])
            if word == "pois":
                L = have.get(ln)
                used.add(ln)
                frames = _int(L[2]) if L else 0
                ra = [_pois(ra[0], frames), _pois(ra[1], frames), ra[2]]
                rb = [_pois(rb[0], frames), _pois(rb[1], frames), rb[2]]
                emit(self.S.get("strModPoisonDamageRange", "Adds %d-%d poison damage over %d seconds"),
                     [0, 1, str(int(round(frames / 25.0)))], [ra, rb], stat_prio(prio_stat))
                return True
            if ln:
                used.add(ln)
            emit(self.S.get(rng_key), [0, 1], [ra, rb], stat_prio(prio_stat))
            return True

        pair("fire-min", "fire-max", None, "fire", "strModFireDamageRange", None, "firemindam")
        pair("ltng-min", "ltng-max", None, "ltng", "strModLightningDamageRange", None, "lightmindam")
        pair("cold-min", "cold-max", "cold-len", "cold", "strModColdDamageRange", None, "coldmindam")
        pair("pois-min", "pois-max", "pois-len", "pois", "strModPoisonDamageRange", None, "poisonmindam")

        # the game's GROUPS (itemstatcost `dgrp`): four equal attributes print as "+N to all Attributes", four equal
        # resistances as "All Resistances +N". Only FIXED values can be equal; a rolled range never groups.
        single = {}
        for (key, code, par, lo, hi) in props:
            p = self.P.get(code) or {}
            if _int(p.get("func1")) == 1 and not p.get("stat2") and p.get("stat1"):
                single.setdefault(p["stat1"], (code, _int(lo), _int(hi)))
        groups = {}
        for st, r in self.I.items():
            if r.get("dgrp"):
                groups.setdefault(r["dgrp"], []).append(st)
        grouped = set()
        for g, members in sorted(groups.items()):
            got = [single.get(st) for st in members]
            if not all(got) or len(set((x[1], x[2]) for x in got)) != 1 or got[0][1] != got[0][2]:
                continue
            d0 = self.I[members[0]]
            fmt = self.S.get(d0.get("dgrpstrpos") or "")
            if not fmt:
                continue
            v = got[0][1]
            k0 = have[got[0][0]][0]
            cur[0] = "+".join(x[0] for x in got)
            emit(fmt, [0], [[v, v, k0]], max(_int(self.I[m].get("descpriority")) for m in members))
            grouped.update(x[0] for x in got)

        for (key, code, par, lo, hi) in props:
            if code in used and code in ("fire-min", "fire-max", "ltng-min", "ltng-max", "cold-min", "cold-max",
                                         "cold-len", "pois-min", "pois-max", "pois-len"):
                continue
            if code in grouped:
                continue
            cur[0] = code
            if code.startswith("*"):
                continue                                  # a row the game itself comments out
            p = self.P.get(code)
            if not p:
                out.append([self.T.id("an effect the game's tables name %s but do not describe" % code), [], 0, 2, code])
                continue
            f1, st1 = _int(p.get("func1")), p.get("stat1") or ""
            d = self.I.get(st1) or {}
            prio = _int(d.get("descpriority"), 0)
            R = rng(lo, hi, key)
            if code in ("dmg-fire", "dmg-ltng", "dmg-cold", "dmg-mag", "dmg-norm", "dmg-pois"):
                word = {"dmg-fire": "Fire", "dmg-ltng": "Lightning", "dmg-cold": "Cold", "dmg-mag": "Magic",
                        "dmg-norm": "Min", "dmg-pois": "Poison"}[code]
                a, b = _int(lo), _int(hi)
                if code == "dmg-pois":
                    frames = _int(par)
                    a, b = _pois(a, frames), _pois(b, frames)
                    fmt = self.S.get("strModPoisonDamageRange") if a != b else self.S.get("strModPoisonDamage")
                    vals = [0, 1, str(int(round(frames / 25.0)))] if a != b else [0, str(int(round(frames / 25.0)))]
                    emit(fmt, vals, [[a, a, key], [b, b, key]] if a != b else [[a, a, key]], prio)
                    continue
                if a != b:
                    emit(self.S.get("strMod%sDamageRange" % word), [0, 1], [[a, a, key], [b, b, key]], prio)
                else:
                    emit(self.S.get("strMod%sDamage" % word), [0], [[a, a, key]], prio)
                continue
            if code == "dmg-elem":
                a, b = _int(lo), _int(hi)
                for word, st in (("Fire", "firemindam"), ("Lightning", "lightmindam"), ("Cold", "coldmindam")):
                    emit(self.S.get("strMod%sDamageRange" % word), [0, 1], [[a, a, key], [b, b, key]], stat_prio(st))
                continue
            if code == "res-all":
                emit(self.S.get("strModAllResistances"), [0], [R], _int(self.I["fireresist"].get("descpriority")))
                continue
            if code == "all-stats":
                emit(self.S.get("Moditem2allattrib"), [0], [R], _int(self.I["strength"].get("descpriority")))
                continue
            if f1 == 7:                                   # dmg%: the game prints one Enhanced Damage line
                emit(self.S.get("strModEnhancedDamage"), [0], [R], stat_prio("item_maxdamage_percent"))
                continue
            if f1 in (5, 6):                              # dmg-min / dmg-max
                st = "mindamage" if f1 == 5 else "maxdamage"
                emit(self.S.get((self.I.get(st) or {}).get("descstrpos") or ""), [0], [R], stat_prio(st))
                continue
            if f1 == 14:                                  # sockets
                n = [_int(par), _int(par), key] if str(par or "").strip() else R
                emit(self.S.get("Socketable", "Socketed (%i)"), [0], [n], 0)
                continue
            if f1 == 20:
                emit(self.S.get("ModStre9s", "Indestructible"), [], [], stat_prio("item_indesctructible"))
                continue
            if f1 == 23:
                emit(self.S.get("strethereal", "Ethereal (Cannot be Repaired)"), [], [], 0, 3)
                continue
            if f1 == 12:                                  # a random skill from an id range
                emit("%+d to a random skill (skill ids " + str(_int(lo)) + "-" + str(_int(hi)) + ")", [0],
                     [[_int(par), _int(par), key]], prio, 2)
                continue
            if f1 == 36:                                  # a random class's skills
                emit("%+d to a random class's Skill Levels", [0], [R], prio, 2)
                continue
            if f1 == 17 and code.endswith("/lvl") or (d.get("descstr2") == "increaseswithplaylevelX"):
                txt = self.S.get(d.get("descstrpos") or "", "")
                if not txt:
                    continue
                tail = self.S.get(d.get("descstr2") or "", "")
                emit(txt + (" " + tail if tail else ""), [0], [["L", _int(par), key]], prio)
                continue
            df = _int(d.get("descfunc"), -1)
            pos = self.S.get(d.get("descstrpos") or "", "")
            neg = self.S.get(d.get("descstrneg") or "", "") or pos
            if df == 19 or df == 1 or df == 2 or df == 3 or df == 4:
                fmt = pos if _int(lo) >= 0 else neg
                if not fmt:
                    continue
                vals = [0] if re.search(r"%[+]?\d*[di]", fmt) else []
                emit(fmt, vals, [R] if vals else [], prio)
            elif df == 29:
                fmt = pos if _int(lo) >= 0 else neg
                emit(fmt, [0], [[abs(R[0]), abs(R[1]), key]] if _int(lo) < 0 else [R], prio)
            elif df == 13:                                # +N to <class> Skill Levels
                ci = _int(p.get("val1"), -1)
                c = self.classes[ci] if 0 <= ci < len(self.classes) else None
                if not c:
                    out.append([self.T.id("class skills for a class index the tables do not name (%s)" % p.get("val1")), [R], prio, 2, code])
                    continue
                emit(c["all"], [0], [R], prio)
            elif df == 14:                                # +N to <tab> Skills (<Class> Only)
                pi = _int(par)
                ci, tab = pi // 3, pi % 3
                c = self.classes[ci] if 0 <= ci < len(self.classes) else None
                if not c:
                    out.append([self.T.id("a skill tab (%s) of a class the tables do not name" % par), [R], prio, 2, code])
                    continue
                emit(c["tabs"][tab] + " " + c["only"], [0], [R], prio)
            elif df in (27, 28, 16):
                sk = self.skill(par)
                if not sk:
                    out.append([self.T.id("a skill (%s) the tables do not name" % par), [R], prio, 2, code])
                    continue
                if df == 27:
                    emit(pos, [0, sk[0], self.class_only(sk[1])], [R], prio)
                elif df == 28:
                    emit(pos, [0, sk[0]], [R], prio)
                else:
                    emit(pos, [0, sk[0]], [R], prio)
            elif df == 15:                                # N% chance to cast level L <skill> on ...
                sk = self.skill(par)
                if not sk:
                    out.append([self.T.id("a chance-to-cast skill (%s) the tables do not name" % par), [], prio, 2, code])
                    continue
                emit(pos, [0, 1, sk[0]], [[_int(lo), _int(lo), key], [_int(hi), _int(hi), key]], prio)
            elif df == 24:                                # Level L <skill> (C/C Charges)
                sk = self.skill(par)
                if not sk:
                    out.append([self.T.id("a charged skill (%s) the tables do not name" % par), [], prio, 2, code])
                    continue
                emit(pos, [0, sk[0], 1, 1], [[_int(hi), _int(hi), key], [_int(lo), _int(lo), key]], prio)
            elif df == 12:
                if _int(lo) == 1 and _int(hi) <= 1:
                    emit(pos, [], [], prio)
                else:
                    emit(pos + " %+d", [0], [R], prio)
            elif df == 11:                                # repairs 1 durability in 100/N seconds
                n = _int(par) or _int(lo)
                if n <= 0:
                    continue
                secs = int(round(100.0 / n))
                emit(self.S.get("ModStre9u", "Repairs %d durability in %d seconds"), ["1", str(secs)], [], prio)
            elif df == 5:                                 # howl: the stat is in 128ths
                emit(pos, [0], [[_int(lo) * 100 // 128, _int(hi) * 100 // 128, key]], prio)
            elif df == 23:                                # reanimate: the monster is an id here
                emit(pos, [0, "monster #" + str(par)], [R], prio, 2)
            else:
                # descfunc empty: the game prints nothing for it (durability, poison length, a visual state)
                continue
        # the game orders lines by descpriority, highest first; ties keep the table's order
        idx = list(range(len(out)))
        idx.sort(key=lambda i: (-out[i][2], i))
        # a line as the block stores it: [template index, ranges, flag, property code] (+ the set-bonus count)
        return [[out[i][0], out[i][1], out[i][3], out[i][4]] for i in idx]

    # ---- the tables -------------------------------------------------------------------------------------------
    def build(self):
        B = {}
        spawnable = set()
        for label in ("armor", "weapons", "misc"):
            for r in _rows(self.blobs[label]):
                code = r.get("code") or ""
                if not code or code in B:
                    continue
                t = r.get("type") or ""
                shown = self.S.get(r.get("namestr") or "") or self.S.get(code) or r.get("name") or code
                fam = [r.get("normcode") or "", r.get("ubercode") or "", r.get("ultracode") or ""]
                tier = fam.index(code) if code in fam else 0
                hands = 0
                if label == "weapons":
                    hands = 12 if r.get("1or2handed") == "1" else (2 if r.get("2handed") == "1" else 1)
                eth = 1 if (label != "misc" and r.get("nodurability") != "1" and _int(r.get("durability")) > 0) else 0
                B[code] = [shown, t, tier, fam, _int(r.get("gemsockets")), _int(r.get("levelreq")),
                           _int(r.get("reqstr")), _int(r.get("reqdex")), _int(r.get("minac")), _int(r.get("maxac")),
                           _int(r.get("mindam")), _int(r.get("maxdam")), _int(r.get("2handmindam")),
                           _int(r.get("2handmaxdam")), hands, _int(r.get("invwidth"), 1),
                           _int(r.get("invheight"), 1), eth, _int(r.get("level")), _int(r.get("block")),
                           1 if r.get("spawnable") == "1" else 0, label[0]]
                if r.get("spawnable") == "1":
                    spawnable.add(code)
        # two bases, one printed name (RotW's Colossal Jewel prints "Jewel"): the later one keeps its TABLE name, so
        # the picker never lists two rows it cannot tell apart
        rows_by_code = dict((r.get("code"), r) for lab in ("armor", "weapons", "misc") for r in _rows(self.blobs[lab])
                            if r.get("code"))
        groups = {}
        for code, b in B.items():
            if b[20]:
                groups.setdefault(b[0], []).append(code)
        for shown, codes in groups.items():
            if len(codes) < 2:
                continue
            for code in codes:
                nm = (rows_by_code.get(code) or {}).get("name") or ""
                if nm and nm != shown:
                    B[code][0] = nm
        self.B = B
        # item types the builder shows: every type a base has, its UI category, class and socket ceiling
        TY = {}
        for code, b in B.items():
            t = b[1]
            if t in TY or t not in self.types:
                continue
            r = self.types[t]
            cc = self.walk(t, "Class")
            TY[t] = [r.get("ItemType") or t, r.get("UICategory") or self.walk(t, "UICategory") or "",
                     self.cls_by_code.get(cc, -1),
                     [_int(r.get("MaxSockets1")), _int(r.get("MaxSocketsLevelThreshold1")),
                      _int(r.get("MaxSockets2")), _int(r.get("MaxSocketsLevelThreshold2")), _int(r.get("MaxSockets3"))],
                     sorted(self.ancestors(t))]
        self.TY = TY
        items = []
        names = {}

        def add(rec):
            items.append(rec)

        # uniques
        for r in _rows(self.blobs["uniqueitems"]):
            if not r.get("index") or r.get("disabled") == "1" or not r.get("code"):
                continue
            if r.get("spawnable") == "0":
                continue                                  # the game never drops it (a legacy Azurewrath, a quest ring)
            if r["code"] not in B:
                continue
            props = [("p%d" % i, r.get("prop%d" % i), r.get("par%d" % i), r.get("min%d" % i), r.get("max%d" % i))
                     for i in range(1, 13) if r.get("prop%d" % i)]
            add(["u" + (r.get("*ID") or str(len(items))), self.S.get(r["index"]) or r["index"], "u", r["code"],
                 _int(r.get("lvl")), _int(r.get("lvl req")), self.lines(props), None, props])
        # sets: the set's own name, its partial bonuses per item
        for r in _rows(self.blobs["setitems"]):
            if not r.get("index") or not r.get("item") or r["item"] not in B:
                continue
            props = [("p%d" % i, r.get("prop%d" % i), r.get("par%d" % i), r.get("min%d" % i), r.get("max%d" % i))
                     for i in range(1, 10) if r.get("prop%d" % i)]
            bonus = []
            for i in range(1, 6):
                for s in "ab":
                    c = r.get("aprop%d%s" % (i, s))
                    if c:
                        ln = self.lines([("a%d%s" % (i, s), c, r.get("apar%d%s" % (i, s)), r.get("amin%d%s" % (i, s)),
                                          r.get("amax%d%s" % (i, s)))], set_bonus=True)
                        for l in ln:
                            l.append(i + 1)             # "(N items)" — worn with N pieces of the set
                        bonus += ln
            add(["s" + (r.get("*ID") or str(len(items))), self.S.get(r["index"]) or r["index"], "s", r["item"],
                 _int(r.get("lvl")), _int(r.get("lvl req")), self.lines(props),
                 {"set": self.S.get(r.get("set") or "") or r.get("set"), "bonus": bonus,
                  "addf": _int(r.get("add func"))}, props])
        # runewords
        rune_code = {}
        for r in _rows(self.blobs["misc"]):
            if r.get("type") == "rune" and r.get("code"):
                rune_code[r["code"]] = r
        for r in _rows(self.blobs["runes"]):
            if r.get("complete") != "1" or not r.get("Name"):
                continue
            runes = [r.get("Rune%d" % i) for i in range(1, 7) if r.get("Rune%d" % i)]
            if not runes or any(x not in rune_code for x in runes):
                continue
            props = [("p%d" % i, r.get("T1Code%d" % i), r.get("T1Param%d" % i), r.get("T1Min%d" % i),
                      r.get("T1Max%d" % i)) for i in range(1, 8) if r.get("T1Code%d" % i)]
            rl = max(_int(rune_code[x].get("levelreq")) for x in runes)
            add(["r" + r["Name"].replace("Runeword", ""), self.S.get(r["Name"]) or r.get("*Rune Name") or r["Name"],
                 "r", "", 0, rl, self.lines(props),
                 {"runes": runes, "it": [r.get("itype%d" % i) for i in range(1, 7) if r.get("itype%d" % i)],
                  "et": [r.get("etype%d" % i) for i in range(1, 4) if r.get("etype%d" % i)],
                  "lad": 1 if str(r.get("firstLadderSeason") or "").strip() and not str(r.get("lastLadderSeason") or "").strip() else 0},
                 props])
        # crafted: cube recipes whose output is a crafted item
        for i, r in enumerate(_rows(self.blobs["cubemain"])):
            if r.get("enabled") != "1" or "crf" not in (r.get("output") or ""):
                continue
            d = r.get("description") or ""
            nm = d.split("->")[-1].strip() if "->" in d else d.strip()
            inp = (r.get("input 1") or "").strip('"').split(",")
            base = inp[0] if inp else ""
            if base in B:
                bref = base
            elif base in self.types:
                bref = "@" + base
            else:
                continue
            props = [("p%d" % k, r.get("mod %d" % k), r.get("mod %d param" % k), r.get("mod %d min" % k),
                      r.get("mod %d max" % k)) for k in range(1, 6) if r.get("mod %d" % k)]
            add(["c%d" % i, nm, "c", bref, _int(r.get("lvl")), 0, self.lines(props),
                 {"upg": 1 if "upg" in inp else 0, "recipe": d}, props])
        # two display names, one item (Rainbow Facet x8): tell them apart by the property that differs
        by = {}
        for rec in items:
            by.setdefault((rec[2], rec[1]), []).append(rec)
        for (q, nm), recs in by.items():
            if len(recs) < 2:
                continue
            for k, rec in enumerate(recs):
                words = [DUP_WORD[c] for (_, c, _, _, _) in rec[8] if c in DUP_WORD]
                rec[1] = "%s (%s)" % (nm, ", ".join(words) if words else "#%d" % (k + 1))
        seen = {}
        for rec in items:
            key = (rec[2], rec[1])
            if key in seen:
                seen[key] += 1
                rec[1] = "%s #%d" % (rec[1], seen[key])
            else:
                seen[key] = 1
        # socketables: runes and gems (gems.txt), by the three slot classes the game gives them
        SK = []
        misc = dict((r["code"], r) for r in _rows(self.blobs["misc"]) if r.get("code"))
        for r in _rows(self.blobs["gems"]):
            code = r.get("code")
            if not code or code not in misc:
                continue
            m = misc[code]
            kind = "rune" if m.get("type") == "rune" else "gem"
            per = []
            for pre in ("weaponMod", "helmMod", "shieldMod"):
                props = [("%s%d" % (pre[0], k), r.get("%s%dCode" % (pre, k)), r.get("%s%dParam" % (pre, k)),
                          r.get("%s%dMin" % (pre, k)), r.get("%s%dMax" % (pre, k))) for k in range(1, 4)
                         if r.get("%s%dCode" % (pre, k))]
                per.append(self.lines(props))
            SK.append([code, self.S.get(m.get("namestr") or "") or self.S.get(code) or m.get("name") or code, kind,
                       _int(m.get("levelreq")), per[0], per[1], per[2]])
        rail = {}
        for slot, cats in SLOT_UI.items():
            rows = []
            for ui in cats:
                if ui == "@offhand":
                    rows.append(["Second Weapons", ["@offhand"], self.cls_by_code.get("bar", -1)])
                    continue
                tys = sorted(t for t, v in TY.items() if v[1] == ui)
                if not tys:
                    continue
                cls = set(TY[t][2] for t in tys)
                rows.append([UI_LABEL.get(ui, ui), tys, cls.pop() if len(cls) == 1 else -1])
            rail[slot] = rows
        inv, said = [], set()
        for t in INV_TYPES:
            if t not in TY:
                continue
            bn = [b[0] for c, b in sorted(B.items()) if b[1] == t]
            label = (bn[0] + "s") if bn else TY[t][0] + "s"
            if label in said:                             # cs2 prints "Grand Charm" too: its TYPE names it apart
                label = TY[t][0] + "s"
            said.add(label)
            inv.append([label, [t], -1])
        rail["inv"] = inv
        for rec in items:
            rec.pop()                                     # the raw props were for naming only
        return {
            "v": 1, "gen": "tv/char_builder_db.py", "cls": self.classes, "ty": TY, "rail": rail, "b": B,
            "T": self.T.list, "it": items, "sk": SK,
            "counts": {"bases": len(B), "uniques": sum(1 for x in items if x[2] == "u"),
                       "sets": sum(1 for x in items if x[2] == "s"), "runewords": sum(1 for x in items if x[2] == "r"),
                       "crafted": sum(1 for x in items if x[2] == "c"), "socketables": len(SK)},
        }


def build():
    """-> (db dict, None) or (None, why). Pulls; writes nothing."""
    blobs = _pull_all()
    absent = [label for label, _ in SOURCES if blobs.get(label) is None]
    if absent:
        return None, ("could not pull %s from the install — the builder's database is UNKNOWN here, not empty"
                      % ", ".join(absent))
    db = DB(blobs).build()
    db["sourceHash"] = source_hash(blobs)
    return db, None


def render(db):
    """the block, byte for byte, as it sits in bible.html (markers included). `</` is escaped so no string in the
    data can close the script element."""
    body = json.dumps(db, ensure_ascii=False, separators=(",", ":"), sort_keys=True).replace("</", "<\\/")
    return (MARK_OPEN + " from the D2R CASC (excel + strings) — do not hand-edit, re-run the generator -->\n"
            + '<script type="application/json" id="%s">' % BLOCK_ID + body + "</script>\n" + MARK_CLOSE)


def _span(src):
    if src.count(MARK_OPEN) != 1 or src.count(MARK_CLOSE) != 1:
        return None
    i = src.index(MARK_OPEN)
    return i, src.index(MARK_CLOSE, i) + len(MARK_CLOSE)


def embedded(src=None):
    """-> the db dict bible.html carries, or None"""
    if src is None:
        with io.open(BIBLE, encoding="utf-8") as f:
            src = f.read()
    sp = _span(src)
    if not sp:
        return None
    blk = src[sp[0]:sp[1]]
    a = blk.index('id="%s">' % BLOCK_ID) + len('id="%s">' % BLOCK_ID)
    b = blk.index("</script>", a)
    return json.loads(blk[a:b])


def check():
    """-> (code, say). 0 the block is what the install says · 1 it is not · 77 cannot tell (NOT green)."""
    try:
        have = embedded()
    except ValueError as e:
        return 1, "the builder's database block does not parse (%s)" % e
    if have is None:
        return 1, "bible.html carries no ⟦CB_DB⟧ block (or carries two) — the builder has nothing to list"
    fresh, why = build()
    if fresh is None:
        return SKIP, "cannot re-derive here (%s), so whether the block matches the install is UNKNOWN" % why
    if fresh == have:
        c = fresh["counts"]
        return 0, ("the builder's database matches the install (%d bases, %d uniques, %d set items, %d runewords, "
                   "%d crafted recipes, %d socketables; source %s)" % (c["bases"], c["uniques"], c["sets"],
                                                                       c["runewords"], c["crafted"], c["socketables"],
                                                                       fresh["sourceHash"][:12]))
    diff = [k for k in sorted(set(fresh) | set(have)) if fresh.get(k) != have.get(k)]
    return 1, "the install disagrees with the block in bible.html (%s differ) — run --write" % ", ".join(diff)


def write():
    if os.path.exists(LOCK):
        return 1, "bible.html.EDIT_LOCK is held — another writer owns bible.html; nothing written"
    fresh, why = build()
    if fresh is None:
        return SKIP, "not written: %s" % why
    with io.open(BIBLE, encoding="utf-8") as f:
        src = f.read()
    sp = _span(src)
    if not sp:
        return 1, "the ⟦CB_DB⟧ markers are not in bible.html exactly once — refusing to guess where it goes"
    new = src[:sp[0]] + render(fresh) + src[sp[1]:]
    if new == src:
        return 0, "already current"
    from bump_version import atomic_write
    atomic_write(BIBLE, new)
    c = fresh["counts"]
    return 0, "wrote the builder's database: %s" % ", ".join("%d %s" % (v, k) for k, v in sorted(c.items()))


def main(argv):
    if "--dump" in argv:
        db, why = build()
        if db is None:
            print("   ⚠ " + why)
            return SKIP
        sys.stdout.write(render(db))
        return 0
    code, say = write() if "--write" in argv else check()
    print(("   ✅ " if code == 0 else "   ⚠ ") + say)
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
