# -*- coding: utf-8 -*-
"""RESUME_HERE.md's live half, DERIVED — because a hand-written resume goes stale and lies.

⚠⚠ MEASURED 2026-09-20: RESUME_HERE.md was FOUR DAYS OLD and described a different set of
unpushed commits. Nothing noticed, because nothing could — it was prose. His ruling, the same one
that produced BLUEPRINT.md and HEART.md: *"we need it all updated and blueprints updated and heart
updated all derived from the console"*, *"fix this so it is like blueprints too and has
enforcement"*. This is that, for the resume.

The split matters and is the whole design:
  · the DERIVED block is regenerated and must never be hand-edited — it is what a machine can
    measure about right now.
  · everything OUTSIDE the markers is narrative a machine cannot derive — why a thing is blocked,
    what was already refuted. That half is written by hand and dated, and it stays.

⚠ NO NETWORK. This never fetches. `origin/main` is whatever the last fetch left in the ref, so
the block SAYS how old that knowledge is rather than implying it is current — a reading carries
the age of the thing it measured. [[stale-reading]]
"""
import io
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# ⚠ THIS PRINTS A CLOCK GLYPH AND WARNING SIGNS. On a cp1255 console that crashes WHILE
# REPORTING, so a clean tree exits non-zero for a reason unrelated to the check — and his Windows
# box is exactly such a console. The pre-push gate refused this file for precisely that, which is
# the gate doing its job. Second time today: the same trap caught a gate file hours ago.
if HERE not in sys.path:
    sys.path.insert(0, HERE)
try:
    from console_safe import enable as _console_safe_enable
    _console_safe_enable()
except Exception:
    pass
RESUME = os.path.join(REPO, "RESUME_HERE.md")
BEGIN = "<!-- BEGIN DERIVED — regenerated by tv/resume_state.py; do not hand-edit -->"
END = "<!-- END DERIVED -->"


def _git(*args):
    """-> stdout, or None when git could not answer. NEVER "" for a failure.

    ⚠⚠ v3413 — AN EMPTY STRING MADE THIS FILE TELL A NEW SESSION THE OPPOSITE OF THE TRUTH.
    A failed run returned "", and `derived()` renders that as `working tree CLEAN` and
    `✅ Nothing is waiting to be pushed` — a false all-clear on the ONE file a resuming session
    trusts to say what has not shipped. Two holes: the except swallowed into "", and the
    returncode was never read, so a git exiting non-zero with empty stdout came back down the
    SUCCESS path. Same shape as v3409's _pull_once finding, in a different file.

    Found by READING CI AFTER THE PUSH: Routine M (the swallowed-exception ratchet) reported
    RANK 1, baseline 69 -> now 70, and named the site. ⚠ Its first run ever was on 0520ce20 —
    502aa2b2 and bad246d5 have runs=0 — so this is a gate arriving, not a regression; the line
    itself dates to v3401. [[unknown-stays-unknown]] [[sweep-dont-ask]]
    """
    try:
        r = subprocess.run(["git"] + list(args), cwd=REPO, capture_output=True,
                           text=True, encoding="utf-8", errors="replace", timeout=20)
    except Exception:
        return None
    if r.returncode != 0:
        return None
    return (r.stdout or "").strip()


def _fetch_age():
    """How stale is our knowledge of origin/main? -> human string, never a guess."""
    for rel in ("FETCH_HEAD", os.path.join("refs", "remotes", "origin", "main")):
        p = os.path.join(REPO, ".git", rel)
        if os.path.isfile(p):
            mins = (time.time() - os.path.getmtime(p)) / 60.0
            if mins < 90:
                return "%.0f min ago" % mins
            return "%.1f h ago" % (mins / 60.0)
    return "UNKNOWN — never fetched in this clone"


def derived():
    head = _git("rev-parse", "--short", "HEAD")
    origin = _git("rev-parse", "--short", "origin/main")
    # ⚠ None means GIT COULD NOT ANSWER and must stay distinguishable from an empty result all
    # the way to the page. `"".split()` yields [] and [] renders as "nothing unpushed" / "CLEAN",
    # which is the false all-clear this version exists to kill.
    _ahead_raw = _git("log", "--oneline", "origin/main..HEAD")
    _dirty_raw = _git("status", "--porcelain")
    ahead = None if _ahead_raw is None else [l for l in _ahead_raw.split("\n") if l.strip()]
    dirty = None if _dirty_raw is None else [l for l in _dirty_raw.split("\n") if l.strip()]
    # ⚠ THE STAMP LIVES IN tv_diablo.py, NOT IN A VERSION FILE. The first cut read a
    # repo-root VERSION that does not exist and cheerfully printed "UNKNOWN" — a generator that
    # reports UNKNOWN for something knowable is worse than one that refuses, because UNKNOWN
    # reads as "nobody could tell" when the truth was "I looked in the wrong place".
    # Read by REGEX, not import: importing tv_diablo drags the whole engine in.
    ver = "UNKNOWN — could not read the stamp"
    try:
        _src = io.open(os.path.join(HERE, "tv_diablo.py"), encoding="utf-8").read()
        _m = re.findall(r'(?m)^VERSION\s*=\s*"(v[0-9.]+)"', _src)
        if len(_m) == 1:
            ver = _m[0]
        elif _m:
            ver = "AMBIGUOUS — %d VERSION lines" % len(_m)
    except Exception:
        pass
    gates = "UNKNOWN"
    try:
        import sys
        if HERE not in sys.path:
            sys.path.insert(0, HERE)
        import run_gates
        gates = str(len(run_gates.GATES))
    except Exception:
        pass

    # ⚠⚠ A FINGERPRINT OF THE FACTS, NOT OF THE RENDERING. The block also prints a derive
    # timestamp and "as known N min ago", both of which change every minute — comparing the whole
    # block would report STALE constantly, and a gate that is always red is switched off within a
    # week, exactly like one that is always green. So staleness is judged on the DURABLE identity
    # of where we are: which commit, which origin, which version. `dirty` is deliberately OUT —
    # uncommitted files are normal mid-work and must not make the resume read as rotten.
    fp = "head=%s origin=%s ver=%s" % (head or "UNKNOWN", origin or "UNKNOWN", ver)
    L = [BEGIN, "<!-- fp: %s -->" % fp, ""]
    L.append("| | |")
    L.append("|---|---|")
    # ⚠⚠ v3416 — ONE FAILED READ, ONE RENDERING. This block used to say a failed `rev-parse`
    # THREE different ways at once: the fingerprint wrote `head=UNKNOWN`, these two cells wrote
    # `?`, and the rows below wrote **UNKNOWN — git could not answer**. A reader comparing the
    # cell against the fingerprint saw two different answers to one question. Found by the
    # second eye at full reach. [[unknown-stays-unknown]] [[copy-drift]]
    _UNK = "**UNKNOWN — git could not answer**"
    L.append("| HEAD | %s |" % (("`%s`" % head) if head else _UNK))
    L.append("| origin/main | %s  ⏱ *as known %s — this never fetches* |"
             % ((("`%s`" % origin) if origin else _UNK), _fetch_age()))
    L.append("| **unpushed** | %s |"
             % ("**UNKNOWN — git could not answer**" if ahead is None
                else "**%d commit(s)**" % len(ahead)))
    L.append("| working tree | %s |"
             % ("**UNKNOWN — git could not answer**" if dirty is None
                else ("CLEAN" if not dirty else "**%d file(s) uncommitted**" % len(dirty))))
    L.append("| version stamp | %s |" % ver)
    L.append("| gates registered | %s |" % gates)
    L.append("")
    if ahead:
        L.append("**Commits that exist only here:**")
        L.append("")
        L.append("```")
        L.extend(ahead[:12])
        if len(ahead) > 12:
            L.append("... and %d more" % (len(ahead) - 12))
        L.append("```")
        L.append("")
        L.append("⚠ **Nothing has shipped until `origin/main` equals `HEAD`.** Verify BY THE REF "
                 "(`git fetch -q origin && git rev-parse --short origin/main`), never by a push's "
                 "exit code — `git push | tail` reports tail's status.")
    elif ahead is None:
        L.append("⚠ **git could not be asked what is unpushed, so this says NOTHING about "
                 "whether work is waiting.** Do not read the absence of a list as an all-clear — "
                 "run `git fetch -q origin && git rev-parse --short origin/main` by hand.")
    else:
        L.append("✅ Nothing is waiting to be pushed — as of the fetch above.")
    L.append("")
    L.append("*Derived %s by `tv/resume_state.py`. Everything outside these markers is narrative "
             "a machine cannot measure, written by hand.*" % time.strftime("%Y-%m-%d %H:%M"))
    L.append("")
    L.append(END)
    return "\n".join(L)


def write(path=RESUME):
    """Replace the derived block in place. -> (changed, why)"""
    block = derived()
    try:
        src = io.open(path, encoding="utf-8").read()
    except Exception:
        io.open(path, "w", encoding="utf-8").write(block + "\n")
        return True, "created"
    if BEGIN in src and END in src:
        a, b = src.index(BEGIN), src.index(END) + len(END)
        out = src[:a] + block + src[b:]
    else:
        # first run: put it directly under the title so a reader meets the state first
        lines = src.split("\n")
        cut = 1 if lines and lines[0].startswith("#") else 0
        out = "\n".join(lines[:cut]) + "\n\n" + block + "\n" + "\n".join(lines[cut:])
    if out == src:
        return False, "already current"
    io.open(path, "w", encoding="utf-8").write(out)
    return True, "regenerated"


if __name__ == "__main__":
    import sys
    if "--check" in sys.argv:
        try:
            src = io.open(RESUME, encoding="utf-8").read()
        except Exception:
            print("RESUME_HERE.md is missing — run: python3 tv/resume_state.py"); sys.exit(2)
        if BEGIN not in src:
            print("RESUME_HERE.md carries no derived block — run: python3 tv/resume_state.py")
            sys.exit(2)
        import re as _re
        have = _re.search(r"<!-- fp: (.*?) -->", src)
        want = _re.search(r"<!-- fp: (.*?) -->", derived())
        if not have or not want:
            print("RESUME_HERE.md carries no fingerprint — run: python3 tv/resume_state.py")
            sys.exit(2)
        if have.group(1) != want.group(1):
            print("RESUME_HERE.md is STALE.\n  it says : %s\n  truth is: %s\n"
                  "  run: python3 tv/resume_state.py" % (have.group(1), want.group(1)))
            sys.exit(1)
        print("resume state is current")
        sys.exit(0)
    changed, why = write()
    print("RESUME_HERE.md %s" % why)
