# -*- coding: utf-8 -*-
"""RESUME_HERE.md's live half, DERIVED — because a hand-written resume goes stale and lies.

⚠⚠ MEASURED 2026-09-20: RESUME_HERE.md was FOUR DAYS OLD and described a different set of
unpushed commits. Nothing noticed, because nothing could — it was prose. His ruling, the same one
that produced BLUEPRINT.md and HEART.md: *"we need it all updated and blueprints updated and heart
updated all derived from the console"*, *"fix this so it is like blueprints too and has
enforcement"*. This is that, for the resume.

The split matters and is the whole design:
  · the DERIVED block is regenerated and must never be hand-edited — it is what a machine can
    measure about right now.
  · everything OUTSIDE the markers is narrative a machine cannot derive — why a thing is blocked,
    what was already refuted. That half is written by hand and dated, and it stays.

⚠ NO NETWORK. This never fetches. `origin/main` is whatever the last fetch left in the ref, so
the block SAYS how old that knowledge is rather than implying it is current — a reading carries
the age of the thing it measured. [[stale-reading]]
"""
import io
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# ⚠ THIS PRINTS A CLOCK GLYPH AND WARNING SIGNS. On a cp1255 console that crashes WHILE
# REPORTING, so a clean tree exits non-zero for a reason unrelated to the check — and his Windows
# box is exactly such a console. The pre-push gate refused this file for precisely that, which is
# the gate doing its job. Second time today: the same trap caught a gate file hours ago.
if HERE not in sys.path:
    sys.path.insert(0, HERE)
try:
    from console_safe import enable as _console_safe_enable
    _console_safe_enable()
except Exception:
    pass
RESUME = os.path.join(REPO, "RESUME_HERE.md")
BEGIN = "<!-- BEGIN DERIVED — regenerated by tv/resume_state.py; do not hand-edit -->"
END = "<!-- END DERIVED -->"


def _git(*args):
    """-> stdout, or None when git could not answer. NEVER "" for a failure.

    ⚠⚠ v3413 — AN EMPTY STRING MADE THIS FILE TELL A NEW SESSION THE OPPOSITE OF THE TRUTH.
    A failed run returned "", and `derived()` renders that as `working tree CLEAN` and
    `✅ Nothing is waiting to be pushed` — a false all-clear on the ONE file a resuming session
    trusts to say what has not shipped. Two holes: the except swallowed into "", and the
    returncode was never read, so a git exiting non-zero with empty stdout came back down the
    SUCCESS path. Same shape as v3409's _pull_once finding, in a different file.

    Found by READING CI AFTER THE PUSH: Routine M (the swallowed-exception ratchet) reported
    RANK 1, baseline 69 -> now 70, and named the site. ⚠ Its first run ever was on 0520ce20 —
    502aa2b2 and bad246d5 have runs=0 — so this is a gate arriving, not a regression; the line
    itself dates to v3401. [[unknown-stays-unknown]] [[sweep-dont-ask]]
    """
    try:
        r = subprocess.run(["git"] + list(args), cwd=REPO, capture_output=True,
                           text=True, encoding="utf-8", errors="replace", timeout=20)
    except Exception:
        return None
    if r.returncode != 0:
        return None
    return (r.stdout or "").strip()


def _fetch_age():
    """How stale is our knowledge of origin/main? -> human string, never a guess."""
    for rel in ("FETCH_HEAD", os.path.join("refs", "remotes", "origin", "main")):
        p = os.path.join(REPO, ".git", rel)
        if os.path.isfile(p):
            mins = (time.time() - os.path.getmtime(p)) / 60.0
            if mins < 90:
                return "%.0f min ago" % mins
            return "%.1f h ago" % (mins / 60.0)
    return "UNKNOWN — never fetched in this clone"


def live():
    """What git says RIGHT NOW. -> dict. Printed by --live; NEVER written into RESUME_HERE.md.

    ⚠⚠ v3474 (#164) — A FILE INSIDE A COMMIT CANNOT NAME THAT COMMIT. The derived block used to state
    HEAD, origin/main, what is unpushed and whether the tree is clean. MEASURED 2026-09-23 after four
    ships: it said head=b6f9405c origin=b7de9f7d, the truth was a629e00a / a629e00a — the head is the
    commit BEFORE the one carrying the text (the sha does not exist until that commit is made), and
    origin is whatever it was before the push (the bump always runs first). Wrong on every ship, by
    construction, and CI's test_the_resume_cannot_go_stale was red for exactly that. So those four
    facts are no longer written down; they are ASKED, at read time. [[stale-reading]]
    """
    ahead_raw = _git("log", "--oneline", "origin/main..HEAD")
    dirty_raw = _git("status", "--porcelain")
    return {"head": _git("rev-parse", "--short", "HEAD"),
            "origin": _git("rev-parse", "--short", "origin/main"),
            "ahead": None if ahead_raw is None else [l for l in ahead_raw.split("\n") if l.strip()],
            "dirty": None if dirty_raw is None else [l for l in dirty_raw.split("\n") if l.strip()],
            "fetched": _fetch_age()}


def _stamp():
    ver = "UNKNOWN — could not read the stamp"
    try:
        _src = io.open(os.path.join(HERE, "tv_diablo.py"), encoding="utf-8").read()
        _m = re.findall(r'(?m)^VERSION\s*=\s*"(v[0-9.]+)"', _src)
        if len(_m) == 1:
            ver = _m[0]
        elif _m:
            ver = "AMBIGUOUS — %d VERSION lines" % len(_m)
    except Exception:
        pass
    gates = "UNKNOWN"
    try:
        if HERE not in sys.path:
            sys.path.insert(0, HERE)
        import run_gates
        gates = str(len(run_gates.GATES))
    except Exception:
        pass
    return ver, gates


def derived():
    """The block written INTO RESUME_HERE.md — only what is knowable when it is written. -> str"""
    ver, gates = _stamp()
    # ⚠ v3474 — THE FINGERPRINT CARRIES ONLY WHAT THE WRITER CAN KNOW. `ver` is chosen BY the bump
    # that writes this block, so it is right at write time and stays right. head/origin were the
    # two fields that were wrong on every ship; they are gone from here, not merely hidden.
    fp = "ver=%s" % ver
    L = [BEGIN, "<!-- fp: %s -->" % fp, ""]
    L.append("| | |")
    L.append("|---|---|")
    L.append("| version stamp | %s |" % ver)
    L.append("| gates registered | %s *(when this was written — ask run_gates for now)* |" % gates)
    L.append("")
    L.append("⚠ **HEAD, origin/main, what is unpushed and whether the tree is clean are NOT written "
             "here.** A file inside a commit cannot name that commit, and the push always runs "
             "after the bump, so this block was wrong about all four on every ship (#164). Ask git, "
             "now:")
    L.append("")
    L.append("    python3 tv/resume_state.py --live")
    L.append("")
    L.append("⚠ **Nothing has shipped until `origin/main` equals `HEAD`.** Verify BY THE REF "
             "(`git fetch -q origin && git rev-parse --short origin/main`), never by a push's exit "
             "code — `git push | tail` reports tail's status.")
    L.append("")
    L.append("*Derived %s by `tv/resume_state.py`. Everything outside these markers is narrative "
             "a machine cannot measure, written by hand.*" % time.strftime("%Y-%m-%d %H:%M"))
    L.append("")
    L.append(END)
    return "\n".join(L)


def print_live():
    st = live()
    unk = "UNKNOWN — git could not answer"
    print("HEAD          %s" % (st["head"] or unk))
    print("origin/main   %s   (as known %s — this never fetches)" % (st["origin"] or unk, st["fetched"]))
    if st["ahead"] is None:
        print("unpushed      %s" % unk)
    else:
        print("unpushed      %d commit(s)" % len(st["ahead"]))
        for l in st["ahead"][:12]:
            print("                %s" % l)
    print("working tree  %s" % (unk if st["dirty"] is None else
                                ("CLEAN" if not st["dirty"] else "%d file(s) uncommitted" % len(st["dirty"]))))
    # ⚠ THE TWO SENTENCES v3413 BUILT INTO THE BLOCK, MOVED HERE WITH THE FACTS THEY QUALIFY.
    # A git that could not be asked must never read as an all-clear. [[unknown-stays-unknown]]
    if st["ahead"] is None:
        print("⚠ git could not be asked what is unpushed, so this says NOTHING about whether work "
              "is waiting - run `git fetch -q origin && git rev-parse --short origin/main` by hand.")
    elif not st["ahead"]:
        print("✅ Nothing is waiting to be pushed — as of the fetch above.")
    return 0

def write(path=RESUME):
    """Replace the derived block in place. -> (changed, why)"""
    block = derived()
    try:
        src = io.open(path, encoding="utf-8").read()
    except Exception:
        io.open(path, "w", encoding="utf-8").write(block + "\n")
        return True, "created"
    if BEGIN in src and END in src:
        a, b = src.index(BEGIN), src.index(END) + len(END)
        out = src[:a] + block + src[b:]
    else:
        # first run: put it directly under the title so a reader meets the state first
        lines = src.split("\n")
        cut = 1 if lines and lines[0].startswith("#") else 0
        out = "\n".join(lines[:cut]) + "\n\n" + block + "\n" + "\n".join(lines[cut:])
    if out == src:
        return False, "already current"
    io.open(path, "w", encoding="utf-8").write(out)
    return True, "regenerated"


if __name__ == "__main__":
    import sys
    if "--live" in sys.argv:
        sys.exit(print_live())
    if "--check" in sys.argv:
        try:
            src = io.open(RESUME, encoding="utf-8").read()
        except Exception:
            print("RESUME_HERE.md is missing — run: python3 tv/resume_state.py"); sys.exit(2)
        if BEGIN not in src:
            print("RESUME_HERE.md carries no derived block — run: python3 tv/resume_state.py")
            sys.exit(2)
        import re as _re
        have = _re.search(r"<!-- fp: (.*?) -->", src)
        want = _re.search(r"<!-- fp: (.*?) -->", derived())
        if not have or not want:
            print("RESUME_HERE.md carries no fingerprint — run: python3 tv/resume_state.py")
            sys.exit(2)
        if have.group(1) != want.group(1):
            print("RESUME_HERE.md is STALE.\n  it says : %s\n  truth is: %s\n"
                  "  run: python3 tv/resume_state.py" % (have.group(1), want.group(1)))
            sys.exit(1)
        print("resume state is current")
        sys.exit(0)
    changed, why = write()
    print("RESUME_HERE.md %s" % why)
